apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-crawler"},"name":"synergychat-crawler","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-crawler"}},"template":{"metadata":{"labels":{"app":"synergychat-crawler"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","name":"synergychat-crawler-1","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]},{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","name":"synergychat-crawler-2","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]},{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","name":"synergychat-crawler-3","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]}],"volumes":[{"emptyDir":{},"name":"cache-volume"}]}}}}
  creationTimestamp: "2024-04-03T22:05:00Z"
  generation: 2
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
  namespace: default
  resourceVersion: "93836"
  uid: 3f76c591-6889-4a56-aacf-ee989e719c8a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-03T22:05:05Z"
    lastUpdateTime: "2024-04-03T22:05:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-03T22:05:00Z"
    lastUpdateTime: "2024-04-04T21:55:38Z"
    message: ReplicaSet "synergychat-crawler-865c55ff49" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
